pluginManagement {
    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://parchmentmc.org'
        }
        maven {
            name = 'Forge'
            url = 'https://minecraftforge.net'
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'hollow_expanse_mod'
